name: Trigger Send Reminder API

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 2 minutes
  workflow_dispatch:       # Allow manual trigger

jobs:
  trigger-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call /send-due-reminders API
        env:
          REMINDER_API_URL: ${{ secrets.REMINDER_API_URL }}
        run: |
          curl -X POST "$REMINDER_API_URL" \
          -H "Content-Type: application/json"
